# -*- coding: utf-8 -*-
"""Lab1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14QzUe9wVNxldSE5zxFbTzL61LCh48evB

# **Підготовка даних**
"""

import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
X, y = iris.data, iris.target

rng = np.random.default_rng(0)

train_indices = []
test_indices = []

for c in [0, 1, 2]:
    c_idx = np.where(y == c)[0]
    shuffled = rng.permutation(c_idx)
    train_indices.extend(shuffled[:35])
    test_indices.extend(shuffled[35:])

X_train, y_train = X[train_indices], y[train_indices]
X_test, y_test = X[test_indices], y[test_indices]

mean = X_train.mean(axis=0)
std = X_train.std(axis=0, ddof=0)

X_train = (X_train - mean) / std
X_test = (X_test - mean) / std

print(f"X_train size: {X_train.shape}, distribution y_train: {np.bincount(y_train)}")
print(f"X_test size: {X_test.shape}, distribution y_test: {np.bincount(y_test)}")
print(f"avg X_train: {np.abs(X_train.mean(axis=0)).round(5)}")
print(f"deviation X_train: {X_train.std(axis=0, ddof=0).round(5)}")

"""# **Ініціалізації параметрів нашої нейронної мережі**"""

rng_init = np.random.default_rng(0)

W1 = rng_init.normal(loc=0.0, scale=np.sqrt(2/4), size=(4, 8))

b1 = np.zeros(8)

W2 = rng_init.normal(loc=0.0, scale=np.sqrt(2/(8 + 3)), size=(8, 3))

b2 = np.zeros(3)

print(f"W1: {W1.shape}, b1: {b1.shape}")
print(f"W2: {W2.shape}, b2: {b2.shape}")
print(f"W1[0, 0]: {W1[0, 0]:.6f}")
print(f"W2[0, 0]: {W2[0, 0]:.6f}")

"""# **Прямий прохід та функція втрат**"""

def forward_pass(X, y, W1, b1, W2, b2):
    Z1 = np.dot(X, W1) + b1

    A1 = np.maximum(0, Z1)

    Z2 = np.dot(A1, W2) + b2

    Z2_max = np.max(Z2, axis=1, keepdims=True)
    Z2_shifted = Z2 - Z2_max

    log_probs = Z2_shifted - np.log(np.sum(np.exp(Z2_shifted), axis=1, keepdims=True))

    N = X.shape[0]
    correct_log_probs = log_probs[np.arange(N), y]
    loss = -np.mean(correct_log_probs)

    probs = np.exp(log_probs)

    cache = {
        "X": X,
        "Z1": Z1,
        "A1": A1,
        "probs": probs,
        "y": y
    }

    return loss, cache

loss, cache = forward_pass(X_train, y_train, W1, b1, W2, b2)

print(f"Loss NumPy: {loss:.8f}")

"""# **Ручне обчислення градієнтів**"""

def backward_pass(cache, W2):
    X = cache["X"]
    Z1 = cache["Z1"]
    A1 = cache["A1"]
    probs = cache["probs"]
    y = cache["y"]
    N = X.shape[0]

    dZ2 = probs.copy()
    dZ2[np.arange(N), y] -= 1.0
    dZ2 /= N

    dW2 = np.dot(A1.T, dZ2)
    db2 = np.sum(dZ2, axis=0)
    dA1 = np.dot(dZ2, W2.T)
    dZ1 = dA1 * (Z1 > 0)
    dW1 = np.dot(X.T, dZ1)
    db1 = np.sum(dZ1, axis=0)

    grads = {
        "dW1": dW1,
        "db1": db1,
        "dW2": dW2,
        "db2": db2
    }
    return grads

grads = backward_pass(cache, W2)

print(f"dW1: {grads['dW1'].shape}, dW1[0, 0]: {grads['dW1'][0, 0]:.8f}")
print(f"db1: {grads['db1'].shape}, db1[0]: {grads['db1'][0]:.8f}")
print(f"dW2: {grads['dW2'].shape}, dW2[0, 0]: {grads['dW2'][0, 0]:.8f}")
print(f"db2: {grads['db2'].shape}, db2[0]: {grads['db2'][0]:.8f}")

"""# **Звірка з PyTorch**"""

import torch
import torch.nn as nn

X_tensor = torch.tensor(X_train, dtype=torch.float64)
y_tensor = torch.tensor(y_train, dtype=torch.long)

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(4, 8)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(8, 3)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x

model = Net()
model = model.to(torch.float64)

with torch.no_grad():
    model.fc1.weight.copy_(torch.tensor(W1.T, dtype=torch.float64))
    model.fc1.bias.copy_(torch.tensor(b1, dtype=torch.float64))
    model.fc2.weight.copy_(torch.tensor(W2.T, dtype=torch.float64))
    model.fc2.bias.copy_(torch.tensor(b2, dtype=torch.float64))

criterion = nn.CrossEntropyLoss()
logits = model(X_tensor)
loss_pt = criterion(logits, y_tensor)

loss_pt.backward()

diff_loss = np.abs(loss - loss_pt.item())

dW1_pt = model.fc1.weight.grad.numpy().T
db1_pt = model.fc1.bias.grad.numpy()
dW2_pt = model.fc2.weight.grad.numpy().T
db2_pt = model.fc2.bias.grad.numpy()

diff_dW1 = np.max(np.abs(grads["dW1"] - dW1_pt))
diff_db1 = np.max(np.abs(grads["db1"] - db1_pt))
diff_dW2 = np.max(np.abs(grads["dW2"] - dW2_pt))
diff_db2 = np.max(np.abs(grads["db2"] - db2_pt))

tol = 1e-12

print(f"Loss NumPy:   {loss:.12f}")
print(f"Loss PyTorch: {loss_pt.item():.12f}")
print("-" * 55)
print(f"{'Величина':<12} | {'Макс. абс. різниця':<25} | {'Пройдено'}")
print("-" * 55)
print(f"{'Loss':<12} | {diff_loss:<25.4e} | {diff_loss <= tol}")
print(f"{'Grad W1':<12} | {diff_dW1:<25.4e} | {diff_dW1 <= tol}")
print(f"{'Grad b1':<12} | {diff_db1:<25.4e} | {diff_db1 <= tol}")
print(f"{'Grad W2':<12} | {diff_dW2:<25.4e} | {diff_dW2 <= tol}")
print(f"{'Grad b2':<12} | {diff_db2:<25.4e} | {diff_db2 <= tol}")

"""# **Перевірка окремих градієнтів чисельним диференціюванням**"""

eps = 1e-6
tol = 1e-7

print("-" * 95)
print(f"{'Параметр':<12} | {'Градієнт backward()':<20} | {'Чисельна похідна':<18} | {'Абсолютна різниця':<18} | {'Перевірку пройдено'}")
print("-" * 95)

params_to_check = [
    ("W1[0,0]", W1, (0, 0), grads["dW1"][0, 0]),
    ("b1[0]", b1, (0,), grads["db1"][0]),
    ("W2[0,0]", W2, (0, 0), grads["dW2"][0, 0]),
    ("b2[0]", b2, (0,), grads["db2"][0])
]

for name, param_array, idx, g_manual in params_to_check:
    original_val = param_array[idx]

    param_array[idx] = original_val + eps
    L_plus, _ = forward_pass(X_train, y_train, W1, b1, W2, b2)

    param_array[idx] = original_val - eps
    L_minus, _ = forward_pass(X_train, y_train, W1, b1, W2, b2)

    param_array[idx] = original_val
    g_num = (L_plus - L_minus) / (2 * eps)

    diff = np.abs(g_num - g_manual)
    passed = diff <= tol

    print(f"{name:<12} | {g_manual:<20.8f} | {g_num:<18.8f} | {diff:<18.4e} | {passed}")

"""# **Дослід із навмисною помилкою**"""

def backward_pass_broken(cache, W2):
    X = cache["X"]
    Z1 = cache["Z1"]
    A1 = cache["A1"]
    probs = cache["probs"]
    y = cache["y"]
    N = X.shape[0]

    dZ2 = probs.copy()
    dZ2[np.arange(N), y] -= 1.0

    dW2 = np.dot(A1.T, dZ2)
    db2 = np.sum(dZ2, axis=0)
    dA1 = np.dot(dZ2, W2.T)
    dZ1 = dA1 * (Z1 > 0)
    dW1 = np.dot(X.T, dZ1)
    db1 = np.sum(dZ1, axis=0)

    return {"dW1": dW1, "db1": db1, "dW2": dW2, "db2": db2}

grads_broken = backward_pass_broken(cache, W2)

diff_dW1_broken = np.max(np.abs(grads_broken["dW1"] - dW1_pt))
tol_pt = 1e-12

print("Дослід із навмисною помилкою")
print(f"Loss NumPy залишився незмінним: {loss == loss_pt.item()}")
print(f"Відношення зламаного dW1[0,0] до правильного: {grads_broken['dW1'][0, 0] / grads['dW1'][0, 0]:.1f}")
print(f"PyTorch перевірка (dW1): макс. різниця {diff_dW1_broken:.4e}, Пройдено: {diff_dW1_broken <= tol_pt}")

name, param_array, idx = "W1[0,0]", W1, (0, 0)
original_val = param_array[idx]

param_array[idx] = original_val + eps
L_plus, _ = forward_pass(X_train, y_train, W1, b1, W2, b2)
param_array[idx] = original_val - eps
L_minus, _ = forward_pass(X_train, y_train, W1, b1, W2, b2)
param_array[idx] = original_val

g_num = (L_plus - L_minus) / (2 * eps)
diff_num_broken = np.abs(g_num - grads_broken["dW1"][0, 0])
tol_num = 1e-7

print(f"Чисельна перевірка (W1[0,0]): різниця {diff_num_broken:.4e}, Пройдено: {diff_num_broken <= tol_num}")
